---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
spec:
  destination:
    name: rocklor
  project: default
  source:
    path: namespaces
    repoURL: https://github.com/ben-obrien/ap-vsphere-config-ext
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
