---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: config-vsphere-

resources:
- resources/application_crds.yaml
- resources/application_namespaces.yaml
- resources/application_vcsim.yaml