---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/vmware.swift.com/customresourcesdefinition_tagmanagers.vmware.swift.com.yaml
- resources/vmware.swift.com/customresourcesdefinition_tags.vmware.swift.com.yaml