---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: drsgroups.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Drsgroup
    listKind: DrsgroupList
    plural: drsgroups
    singular: drsgroup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
