---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterhas.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Clusterha
    listKind: ClusterhaList
    plural: clusterhas
    singular: clusterha
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
