---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hostfirewallmanagers.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Hostfirewallmanager
    listKind: HostfirewallmanagerList
    plural: hostfirewallmanagers
    singular: hostfirewallmanager
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
