---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hostkernelmanagers.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Hostkernelmanager
    listKind: HostkernelmanagerList
    plural: hostkernelmanagers
    singular: hostkernelmanager
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
