---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cfgbackups.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Cfgbackup
    listKind: CfgbackupList
    plural: cfgbackups
    singular: cfgbackup
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
