---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: guests.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Guest
    listKind: GuestList
    plural: guests
    singular: guest
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
