---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dvswitchs.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Dvswitch
    listKind: DvswitchList
    plural: dvswitchs
    singular: dvswitch
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
