---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dvshosts.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Dvshost
    listKind: DvshostList
    plural: dvshosts
    singular: dvshost
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
