---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: localusermanagers.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Localusermanager
    listKind: LocalusermanagerList
    plural: localusermanagers
    singular: localusermanager
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
