---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastoreclusters.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Datastorecluster
    listKind: DatastoreclusterList
    plural: datastoreclusters
    singular: datastorecluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
