---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: contentlibrarymanagers.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Contentlibrarymanager
    listKind: ContentlibrarymanagerList
    plural: contentlibrarymanagers
    singular: contentlibrarymanager
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
