---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vcenters.vmware.swift.com
spec:
  group: vmware.swift.com
  names:
    kind: Vcenter
    listKind: VcenterList
    plural: vcenters
    singular: vcenter
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
